/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package anchora.engine.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello owo World :3!";
    }
}
