/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package anchora.engine.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        assertEquals("Hello owo World :3!", MessageUtils.getMessage());
    }
}
